version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - edgedb
    environment:
      - EDGEDB_DSN=edgedb://edgedb:5656

  edgedb:
    image: edgedb/edgedb
    ports:
      - "5656:5656"
    environment:
      EDGEDB_SERVER_SECURITY=insecure_dev_mode
    volumes:
      - edgedb_data:/var/lib/edgedb/data

volumes:
  edgedb_data:

